# Generated by Django 2.0.13 on 2020-01-14 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BizVia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('video_url', models.CharField(max_length=200, null=True)),
                ('video_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'BizVia',
            },
        ),
        migrations.CreateModel(
            name='BusinessSense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('video_url', models.CharField(max_length=200, null=True)),
                ('video_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'BusinessSense',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='EventSpectrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('video_url', models.CharField(max_length=200, null=True)),
                ('video_image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Category')),
            ],
            options={
                'verbose_name': 'EventSpectrum',
            },
        ),
        migrations.CreateModel(
            name='EventTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(blank=True, max_length=200, null=True)),
                ('video_url', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Event TV',
            },
        ),
        migrations.CreateModel(
            name='Exclusive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('video_url', models.CharField(max_length=200, null=True)),
                ('video_image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Category')),
            ],
            options={
                'verbose_name': 'Exclusive',
            },
        ),
        migrations.CreateModel(
            name='HighlightVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(blank=True, max_length=200, null=True)),
                ('video_url', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'HighlightVideo',
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('video_url', models.CharField(max_length=200, null=True)),
                ('video_image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Category')),
            ],
            options={
                'verbose_name': 'Insight',
            },
        ),
        migrations.CreateModel(
            name='SixtySeconds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('video_url', models.CharField(max_length=200, null=True)),
                ('video_image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Category')),
            ],
            options={
                'verbose_name': 'sixtyseconds',
            },
        ),
        migrations.CreateModel(
            name='StartUpNaija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('video_url', models.CharField(max_length=200, null=True)),
                ('video_image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Category')),
            ],
            options={
                'verbose_name': 'StartUpNaija',
            },
        ),
        migrations.AddField(
            model_name='businesssense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Category'),
        ),
        migrations.AddField(
            model_name='bizvia',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Category'),
        ),
    ]
