# Generated by Django 2.0.13 on 2020-01-14 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('payment_status', models.CharField(choices=[('S', 'Success'), ('F', 'Failed')], max_length=50)),
                ('ticket', models.FileField(blank=True, null=True, upload_to='documents')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.EventPage')),
            ],
        ),
    ]
