# Generated by Django 2.0.13 on 2020-01-14 08:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('page_banner', models.ImageField(blank=True, max_length=200, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='')),
                ('content_title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('page_banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('content_title', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeadsPearls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('button', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CakeFair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('button', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CTASession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('background', models.ImageField(max_length=200, null=True, upload_to='')),
                ('button_title', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Parallax Section',
                'verbose_name_plural': 'Parallax Section',
            },
        ),
        migrations.CreateModel(
            name='FlowerConvention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('button', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('button', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_banner', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicConvention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('button', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerLogos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_image', models.ImageField(max_length=200, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Partner Logo',
                'verbose_name_plural': 'Partner Logos',
            },
        ),
        migrations.CreateModel(
            name='TopVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('video', models.CharField(max_length=200)),
                ('video_image', models.ImageField(max_length=200, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Top Video',
                'verbose_name_plural': 'Top Videos',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('page_banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('content_title', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('evt_video', models.CharField(blank=True, max_length=200, null=True)),
                ('evt_video_image', models.ImageField(blank=True, max_length=200, null=True, upload_to='')),
                ('linked_page', models.CharField(blank=True, max_length=200, null=True)),
                ('button_text', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Welcome Block',
                'verbose_name_plural': 'Welcome Block',
            },
        ),
    ]
