# Generated by Django 2.0.13 on 2020-01-14 08:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(max_length=250)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='SmeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('banner_title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmeCircuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(max_length=250)),
                ('page_banner', models.ImageField(blank=True, upload_to='')),
                ('content_image', models.ImageField(upload_to='')),
                ('body', ckeditor.fields.RichTextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sme.Category')),
            ],
            options={
                'verbose_name': 'SME Circuit',
                'verbose_name_plural': 'SME Circuit',
            },
        ),
        migrations.CreateModel(
            name='SmeLandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(max_length=250)),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('body', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'SME Landing Page',
                'verbose_name_plural': 'SME Landing Page',
            },
        ),
        migrations.CreateModel(
            name='SmeThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('linked_page', models.CharField(max_length=120)),
            ],
        ),
    ]
