# Generated by Django 2.0.13 on 2020-01-14 08:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(max_length=250)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, verbose_name='')),
                ('slug', models.SlugField(max_length=250)),
                ('track_record', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('business_address', models.TextField()),
                ('state', models.CharField(blank=True, max_length=120, null=True, verbose_name='')),
                ('city', models.CharField(blank=True, max_length=120, null=True, verbose_name='')),
                ('company_logo', models.ImageField(blank=True, default='directory/default_logo.jpg', null=True, upload_to='directory')),
                ('product_image', models.ImageField(blank=True, default='directory/default_img.jpg', null=True, upload_to='directory')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Category')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AlterIndexTogether(
            name='directory',
            index_together={('id', 'slug')},
        ),
    ]
